// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamBoat.Data;

namespace SteamBoat.Migrations
{
    [DbContext(typeof(SteamBoatContext))]
    [Migration("20220402175151_sales")]
    partial class sales
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SteamBoat.Models.FeederUrl", b =>
                {
                    b.Property<int>("FeederId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("isJSON")
                        .HasColumnType("bit");

                    b.HasKey("FeederId");

                    b.HasIndex("MissionId");

                    b.ToTable("FeederUrl");
                });

            modelBuilder.Entity("SteamBoat.Models.Item", b =>
                {
                    b.Property<string>("hash_name_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<int>("Fruit")
                        .HasColumnType("int");

                    b.Property<string>("Game")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gap")
                        .HasColumnType("int");

                    b.Property<string>("ItemPageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemStatsURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NumForSale")
                        .HasColumnType("int");

                    b.Property<int>("StartingPrice")
                        .HasColumnType("int");

                    b.Property<int>("bid_price")
                        .HasColumnType("int");

                    b.Property<string>("bid_price_in_pound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bid_quant")
                        .HasColumnType("int");

                    b.Property<string>("item_nameid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("max_buy_price")
                        .HasColumnType("int");

                    b.Property<int>("min_sell_price")
                        .HasColumnType("int");

                    b.Property<int>("next_min_sell_price")
                        .HasColumnType("int");

                    b.Property<int>("orders")
                        .HasColumnType("int");

                    b.HasKey("hash_name_key");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SteamBoat.Models.ItemForSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Game_hash_name_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Itemhash_name_key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("sale_price_after_fees")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Itemhash_name_key");

                    b.ToTable("ItemsForSale");
                });

            modelBuilder.Entity("SteamBoat.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListingsMax")
                        .HasColumnType("int");

                    b.Property<int>("ListingsMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PriceMax")
                        .HasColumnType("int");

                    b.Property<int>("PriceMin")
                        .HasColumnType("int");

                    b.HasKey("MissionId");

                    b.ToTable("Mission");
                });

            modelBuilder.Entity("SteamBoat.Models.FeederUrl", b =>
                {
                    b.HasOne("SteamBoat.Models.Mission", "Mission")
                        .WithMany("FeederUrls")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SteamBoat.Models.ItemForSale", b =>
                {
                    b.HasOne("SteamBoat.Models.Item", null)
                        .WithMany("ItemsForSale")
                        .HasForeignKey("Itemhash_name_key");
                });

            modelBuilder.Entity("SteamBoat.Models.Item", b =>
                {
                    b.Navigation("ItemsForSale");
                });

            modelBuilder.Entity("SteamBoat.Models.Mission", b =>
                {
                    b.Navigation("FeederUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
